# ML Lab (CS360)
## Assignment 1

### PART 1: NumPy Basic

1. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives

In [ ]:
import numpy as np

zeros = np.zeros((10))
print(zeros)

ones = np.ones((10))
print(ones)

fives = np.ones((10)) * 5
print(fives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2. Write a numpy program to create an array of all the even integers from 10 to 50

In [ ]:
array = np.arange(10, 50, 2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


3. Write a NumPy program to generate a random matrix of size 3 X 3 (in which the values are in the range between 0 and 1)

In [ ]:
random_matrix = np.random.random((3, 3))
print(random_matrix)

[[0.42810075 0.42757548 0.97486035]
 [0.6088957  0.423715   0.94995746]
 [0.16839255 0.31420931 0.22196605]]


4. Write a NumPy program to save the matrix (generated in question 3) to a text file and load it.

In [ ]:
np.savetxt("foobar.csv", random_matrix, delimiter=",")
random_matrix = np.loadtxt("foobar.csv", delimiter=",")
print(random_matrix)

[[0.42810075 0.42757548 0.97486035]
 [0.6088957  0.423715   0.94995746]
 [0.16839255 0.31420931 0.22196605]]


### PART 2: Pandas Excel

1. Write a python program to read an image and save the image as a matrix to a .csv file using pandas

In [ ]:
import pandas as pd
from PIL import Image, ImageOps

!wget -P ./ https://4.bp.blogspot.com/-OQZGt_5WqDo/Wa_Dfa4U15I/AAAAAAAAAUI/veRmAmUUKFA19dVw6XCOV2YLO6n-y_omwCLcBGAs/s400/out.jpg

img = np.array(ImageOps.grayscale(Image.open('out.jpg')))

df = pd.DataFrame(data = img)
df.to_csv("img_as_csv")

--2020-08-23 07:09:21--  https://4.bp.blogspot.com/-OQZGt_5WqDo/Wa_Dfa4U15I/AAAAAAAAAUI/veRmAmUUKFA19dVw6XCOV2YLO6n-y_omwCLcBGAs/s400/out.jpg
Resolving 4.bp.blogspot.com (4.bp.blogspot.com)... 74.125.201.132, 2607:f8b0:4001:c01::84
Connecting to 4.bp.blogspot.com (4.bp.blogspot.com)|74.125.201.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 44901 (44K) [image/jpeg]
Saving to: ‘./out.jpg’

out.jpg             100%[===================>]  43.85K  --.-KB/s    in 0s      

2020-08-23 07:09:21 (118 MB/s) - ‘./out.jpg’ saved [44901/44901]



2. Write a program to import excel data from the .csv file (generated in question 1) by excluding the last row and last column

In [ ]:
read_df = pd.read_csv('img_as_csv', skipfooter=1, engine='python', usecols=range(399))

3. Write a Pandas program to create the today's date

In [ ]:
from datetime import date

date_today = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date: " + str(date_today))

Today's date: 2020-08-23 00:00:00


### Part 3

Create a mini calculator to know the age of a person after putting the range (i.e. data of birth and current date)



In [ ]:
import datetime

today_year = int(input("Enter the year today: "))
today_month = int(input("Enter the month today: "))
today_day = int(input("Enter the day today: "))
today = datetime.datetime(today_year, today_month, today_day)

birthdate_year = int(input("Enter your birth year: "))
birthdate_month = int(input("Enter your birth month: "))
birthdate_day = int(input("Enter your birthdate day: "))
birthdate = datetime.datetime(birthdate_year, birthdate_month, birthdate_day)

age = today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day)) 
print("You are " + str(age) + " years old")

Enter the year today: 2020
Enter the month today: 8
Enter the day today: 23
Enter your birth year: 1999
Enter your birth month: 03
Enter your birthdate day: 13
You are 21 years old
