<a href="https://colab.research.google.com/github/ayush1399/CS360-Machine-Learning/blob/master/CS360_Assignment_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Python program to get the Python version you are using.

In [1]:
import sys
print("Python Version")
print (sys.version)

Python Version
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]


2. Write a Python program to locate Python site-packages.

In [2]:
import site
packages = site.getsitepackages()

[print(package) for package in packages]
print("Number of packages: " + str(len(packages)))

/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.6/dist-packages
Number of packages: 3


3. Write a python program to get the path and name of the file that is currently executing.

In [3]:
import os
print("Current File Name : " + os.path.realpath(__file__))

# Not applicable for IPython Jupyter Notebook environments

NameError: ignored

4. Write a python program to randomly generate two matrices of size [2x3 and 3x3] and do the matrix multiplication using the two generated matrices. ) (Say A = BC)

In [4]:
import numpy as np

B = np.random.randint(0, high=100, size=(2, 3))
print("Matrix B: ")
print(B)
print()

C = np.random.randint(0, high=100, size=(3, 3))
print("Matrix C: ")
print(C)
print()

A = np.dot(B, C)
print("Matrix A = BC")
print(A)
print()

Matrix B: 
[[35 17 30]
 [85 27 89]]

Matrix C: 
[[83  2 95]
 [44 72 96]
 [80 32 39]]

Matrix A = BC
[[ 6053  2254  6127]
 [15363  4962 14138]]



5. Use a for loop to implement the above question five times and thereafter take the average of all the five matrices and display the result.

In [5]:
A = list()

for i in range(5):
  B = np.random.randint(0, high=100, size=(2, 3))
  C = np.random.randint(0, high=100, size=(3, 3))
  A.append(np.dot(B, C))

A = np.mean(A, axis=0)

6. Write a program to transfer the matrix (generated in question 5) to the csv file and then read the same matrix and display the transposition of it.

In [6]:
np.savetxt("matrix.csv", A, delimiter=',')
A = np.loadtxt("matrix.csv", delimiter=',')
print(np.transpose(A))

[[ 6740.4  8196. ]
 [ 7093.4  8503.4]
 [ 8142.8 10288.8]]


7. Write a program to find the mean, mode, and median of the above-mentioned matrix.

In [7]:
from scipy import stats

mean = np.mean(A)
median = np.median(A)
mode = stats.mode(A, axis=None).mode[0]
print("Mean: " + str(mean))
print("Median: " + str(median))
print("Mode: " + str(mode))

Mean: 8160.8
Median: 8169.4
Mode: 6740.4


8. Write a program to print the upper triangle of the matrix.

In [8]:
m, n = A.shape

for i in range(m):
  for j in range(i):
    print("      ", end=" ")
  for j in range(n - i):
    print(A[i][j + i], end=" ")
  print()

6740.4 7093.4 8142.8 
       8503.4 10288.8 


9. Write a Python program to read specific columns of a given CSV file and print the content of the columns. (Column number should be given by the user)

In [9]:
inp = input("Enter the column numbers you want to read: ")
inp = inp.split(" ")
inp = [int(num) for num in inp]

A = np.loadtxt("matrix.csv", delimiter=',')
print(A[:, inp])

Enter the column numbers you want to read: 0 2
[[ 6740.4  8142.8]
 [ 8196.  10288.8]]




10. Write a Python program to replace a user-defined number present in the CSV file by the character 'A'.

In [10]:
import csv

A = np.loadtxt("matrix.csv", delimiter=',').tolist()
num = float(input("Which number do you want to replace? "))
for i in range(len(A)):
  for j in range(len(A[i])):
    if A[i][j] == num:
      A[i][j] = 'A'

A = np.array(A)

with open("matrix.csv", "w", newline="\n") as f:
    writer = csv.writer(f)
    writer.writerows(A)

Which number do you want to replace? 8142.8
